name: CatSeedLogin 自动构建

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Archive artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: CatSeedLogin
        path: target/CatSeedLogin.jar

    - name: Automatic Releases
      if: success()
      uses: marvinpinto/action-automatic-releases@v4
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "dev"
        prerelease: false
        title: "CatSeedLogin 自动构建版本"
        files: target/CatSeedLogin.jar